---
- name: Upload Prometheus install script
  copy:
    src: install_prometheus_service_ubuntu.sh
    dest: /tmp/install_prometheus_service_ubuntu.sh
    mode: "0755"

- name: Run Prometheus install script
  command: /tmp/install_prometheus_service_ubuntu.sh

- name: Update prometheus.yaml file
  copy:
    src: prometheus.yaml
    dest: /etc/prometheus/prometheus.yml 

- name: Restart Prometheus service
  service:
    name: prometheus
    state: restarted
    enabled: yes